# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('profile_img', models.ImageField(upload_to='img/team/profile')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('portfolio', models.URLField(blank=True, max_length=300)),
                ('social_media', models.URLField(blank=True, max_length=300)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=101, populate_from=('first_name', 'middle_name', 'last_name'), unique=True)),
                ('interest', models.ManyToManyField(to='team.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Role'),
        ),
    ]
