# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='interest',
        ),
        migrations.AddField(
            model_name='interest',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Member'),
        ),
    ]
