# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20170315_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='member',
        ),
    ]
