# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_interest_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='interest',
            field=models.ManyToManyField(to='team.Interest'),
        ),
    ]
