# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_member_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='interest',
            field=models.ManyToManyField(related_name='interests', to='team.Interest'),
        ),
    ]
