# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20170315_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='interest',
            new_name='interests',
        ),
    ]
