# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20170307_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.EmailField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('address', models.TextField(max_length=255)),
                ('city', models.TextField(max_length=100)),
                ('state', models.TextField(max_length=100)),
                ('country', models.TextField(max_length=100)),
                ('phone', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
