# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20170307_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(default='Haiti', max_length=100),
        ),
    ]
