# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20170307_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Port au Prince', max_length=100),
        ),
    ]
