# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170328_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_on',
            field=models.DateTimeField(default='2017-03-28 10:52:39.423936'),
            preserve_default=False,
        ),
    ]
