# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(),
        ),
    ]
