# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
