# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20170309_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('day', models.ManyToManyField(to='schedule.Day')),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='program',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_time',
        ),
        migrations.AddField(
            model_name='program',
            name='time_slots',
            field=models.ManyToManyField(to='schedule.Slot'),
        ),
    ]
