# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20170314_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='day',
        ),
        migrations.AddField(
            model_name='slot',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.Day'),
        ),
    ]
