# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20170314_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='slot',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.Program'),
            preserve_default=False,
        ),
    ]
