# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20170314_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.Program'),
        ),
    ]
